index:
  path: /
  controller: App\Controller\IndexController::indexAction
cash-up:
  path: /cash-up
  controller: App\Controller\CashUpController::cashUpAction
rota:
  path: /rota
  controller: App\Controller\RotaController::rotaAction
sign-in:
  path: /sign-in
  controller: App\Controller\SignInController::signInAction
weekly-overview:
  path: /weekly-overview
  controller: App\Controller\WeeklyOverviewController::weeklyOverviewAction
user:
  path: /user
  controller: App\Controller\UserController::userAction
role:
  path: /user/role
  controller: App\Controller\UserController::roleAction