index:
  path: /
  controller: App\Controller\IndexController::indexAction
cash-up:
  path: /cash-up
  controller: App\Controller\CashUpController::cashUpAction
  methods: [POST]
cash-up-date:
  path: /cash-up/{dateString}
  controller: App\Controller\CashUpController::cashUpDateAction
  methods: [GET]
rota:
  path: /rota
  controller: App\Controller\RotaController::rotaAction
  methods: [POST]
rota-date:
  path: /rota/{dateString}
  controller: App\Controller\RotaController::rotaDateAction
  methods: [GET]
users:
  path: /users
  controller: App\Controller\UserController::usersAction
  methods: [GET]
user:
  path: /users/user
  controller: App\Controller\UserController::userAction
  methods: [GET, POST]
role:
  path: /users/role
  controller: App\Controller\UserController::roleAction
  methods: [POST]
roles:
  path: /users/roles
  controller: App\Controller\UserController::rolesAction
  methods: [GET]
domain:
  path: /users/domain
  controller: App\Controller\UserController::domainAction
  methods: [POST]
domains:
  path: /users/domains
  controller: App\Controller\UserController::domainsAction
  methods: [GET]
staff-roles:
  path: /staff/roles
  controller: App\Controller\StaffController::staffRolesAction
staff-members:
  path: /staff/members
  controller: App\Controller\StaffController::staffMembersAction
constants:
  path: /constants
  controller: App\Controller\ConstantsController::constantsAction