index:
  path: /
  controller: App\Controller\IndexController::indexAction
cash-up:
  path: /cash-up
  controller: App\Controller\CashUpController::cashUpAction
rota:
  path: /rota
  controller: App\Controller\RotaController::rotaAction
sign-in:
  path: /sign-in
  controller: App\Controller\SignInController::signInAction
weekly-overview:
  path: /weekly-overview
  controller: App\Controller\WeeklyOverviewController::weeklyOverviewAction
users:
  path: /users
  controller: App\Controller\UserController::usersAction
  methods: [GET]
user:
  path: /users/user
  controller: App\Controller\UserController::userAction
role:
  path: /users/role
  controller: App\Controller\UserController::roleAction
roles:
  path: /users/roles
  controller: App\Controller\UserController::rolesAction
  methods: [GET]
domain:
  path: /users/domain
  controller: App\Controller\UserController::domainAction
domains:
  path: /users/domains
  controller: App\Controller\UserController::domainsAction
  methods: [GET]