export enum DateFormats {
  API_DATE = 'YYYY-MM-DD',
  API_DATE_TIME = 'YYYY-MM-DD HH:mm',
  READABLE_WITH_YEAR = 'ddd D MMM Y',
  READABLE_NO_YEAR = 'ddd D MMM',
  DMY_SLASHES = 'DD/MM/YYYY',
  TIME_LEADING_ZERO = 'HH:mm',
  TIME_NO_LEADING_ZERO = 'H:mm',
}