databases:
- name: ploughbooks
  user: dev
  password: secret
folders:
  - map: ../
    to: /vagrant/code
sites:
- url: localhost
  root: /vagrant/code/public
apt-packages:
  - php7.2-xml
ports:
  - guest: 3306
    host: 33060