cash-up:
  path: /api/cash-up
  controller: App\Controller\CashUpController::cashUpAction
  methods: [POST]
cash-up-date:
  path: /api/cash-up/{dateString}
  controller: App\Controller\CashUpController::cashUpDateAction
  methods: [GET]
rota:
  path: /api/rota
  controller: App\Controller\RotaController::rotaAction
  methods: [POST]
weekly-planning:
  path: /api/weekly-planning
  controller: App\Controller\RotaController::weeklyPlanningAction
  methods: [POST]
rota-date:
  path: /api/rota/{dateString}
  controller: App\Controller\RotaController::rotaDateAction
  methods: [GET]
users:
  path: /api/users
  controller: App\Controller\UserController::usersAction
  methods: [GET]
user:
  path: /api/users/user
  controller: App\Controller\UserController::userAction
  methods: [GET, POST]
role:
  path: /api/users/role
  controller: App\Controller\UserRoleController::roleAction
  methods: [POST]
roles:
  path: /api/users/roles
  controller: App\Controller\UserRoleController::rolesAction
  methods: [GET]
domain:
  path: /api/users/domain
  controller: App\Controller\UserDomainController::domainAction
  methods: [POST]
domains:
  path: /api/users/domains
  controller: App\Controller\UserDomainController::domainsAction
  methods: [GET]
staff-roles:
  path: /api/staff/roles
  controller: App\Controller\StaffController::staffRolesAction
staff-members:
  path: /api/staff/members
  controller: App\Controller\StaffController::staffMembersAction
constants:
  path: /api/constants
  controller: App\Controller\ConstantsController::constantsAction
index:
  path: /{foo}
  controller: App\Controller\IndexController::indexAction
  requirements:
    foo: ^(?!.*_profiler).*